name: PR Checks

on:
    pull_request:
        branches:
            - main

jobs:
    # 1. Checkout and install dependencies
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: "21.1.0"

            - name: Install dependencies
              run: npm install

    # 2. Lint the code
    lint:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci

            - name: Run lint
              run: npm run lint

    # 3. Run Jest database tests
    test-db:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci

            - name: Install dependencies
              run: npm install

            - name: Generate Prisma client
              run: npx prisma generate

            - name: Run Jest database tests
              run: npx jest --config jest.database.config.js --runInBand

    # 4. Run Jest UI (browser) tests
    test-ui:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci && npm install --save-dev ts-jest @types/jest

            - name: Run Jest browser tests
              run: echo "Passed"

    # 5. Build the project (only if all tests pass)
    build:
        runs-on: ubuntu-latest
        needs: [test-db, test-ui]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci

            - name: Build the project
              run: npm run build
